# Tasklet Factory Mobile WMS — warehouse mobile scanning solution.

[module]
key = "tasklet"
name = "Tasklet"

[[module.dependencies]]
dep_id = "a5727ce6-368c-49e2-84cb-1a6052f0551c"
dep_name = "Mobile WMS"
dep_publisher = "Tasklet Factory"
dep_version = "1.0.0.0"
