namespace ALDevToolbox.Domain.Entities;

/// <summary>
/// Single-use reset token generated by /forgot-password. The plain-text token
/// is sent in the email; only its SHA-256 hash is persisted, so a database
/// snapshot does not yield usable tokens. <see cref="ConsumedAt"/> is stamped
/// on first successful use; <see cref="ExpiresAt"/> is one hour after issue.
/// </summary>
public class PasswordResetToken
{
    public int Id { get; set; }

    public int UserId { get; set; }
    public User? User { get; set; }

    /// <summary>Hex-encoded SHA-256 of the token value sent to the user.</summary>
    public string TokenHash { get; set; } = string.Empty;

    public DateTime CreatedAt { get; set; }
    public DateTime ExpiresAt { get; set; }
    public DateTime? ConsumedAt { get; set; }
}
