using ALDevToolbox.Domain.Entities;
using ALDevToolbox.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ALDevToolbox.Data.Configurations;

internal sealed class WorkspaceExtensionDependencyConfiguration : IEntityTypeConfiguration<WorkspaceExtensionDependency>
{
    private readonly IOrganizationContext _orgContext;
    public WorkspaceExtensionDependencyConfiguration(IOrganizationContext orgContext) => _orgContext = orgContext;

    public void Configure(EntityTypeBuilder<WorkspaceExtensionDependency> entity)
    {
        entity.ToTable("workspace_extension_dependencies");
        entity.HasKey(e => e.Id);
        entity.Property(e => e.Id).HasColumnName("id").ValueGeneratedOnAdd();
        entity.Property(e => e.OrganizationId).HasColumnName("organization_id").IsRequired();
        entity.Property(e => e.WorkspaceExtensionId).HasColumnName("workspace_extension_id").IsRequired();
        entity.Property(e => e.Ordering).HasColumnName("ordering").IsRequired();
        entity.Property(e => e.RefExtensionPath).HasColumnName("ref_extension_path");
        entity.Property(e => e.RefModuleKey).HasColumnName("ref_module_key");
        entity.Property(e => e.LitId).HasColumnName("lit_id");
        entity.Property(e => e.LitName).HasColumnName("lit_name");
        entity.Property(e => e.LitPublisher).HasColumnName("lit_publisher");
        entity.Property(e => e.LitVersion).HasColumnName("lit_version");
        entity.HasIndex(e => new { e.WorkspaceExtensionId, e.Ordering });
        // Exactly one of the three reference groups must be non-null. The
        // CHECK is added in the UnifyExtensions migration; EF doesn't have
        // a fluent API for table CHECKs, so the constraint lives in raw
        // SQL there and is regenerated by future migrations via
        // AppDbContextModelSnapshot.
        entity.ScopeToOrganization(_orgContext);
    }
}
