// <auto-generated />
using System;
using ALDevToolbox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ALDevToolbox.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260512000000_RuntimeColumnAsString")]
    partial class RuntimeColumnAsString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_by");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("entity_type");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("snapshot_json");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId", "Timestamp")
                        .HasDatabaseName("ix_audit_log_entity_timestamp");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("ix_audit_log_timestamp");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Deprecated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deprecated");

                    b.Property<int?>("IdRangeSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_range_size");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("modules", (string)null);
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.ModuleDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("DepId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_id");

                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_name");

                    b.Property<string>("DepPublisher")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_publisher");

                    b.Property<string>("DepVersion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_version");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("module_id");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordering");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Ordering");

                    b.ToTable("module_dependencies", (string)null);
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.RuntimeTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AppSourceCop")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("app_source_cop_json");

                    b.Property<int>("CoreIdRangeFrom")
                        .HasColumnType("INTEGER")
                        .HasColumnName("core_id_range_from");

                    b.Property<int>("CoreIdRangeTo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("core_id_range_to");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultApplication")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_application");

                    b.Property<string>("DefaultPlatform")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("default_platform");

                    b.Property<string>("Defaults")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("defaults_json");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("Deprecated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("deprecated");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int>("ModuleIdRangeSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("module_id_range_size");

                    b.Property<int>("ModuleIdRangeStart")
                        .HasColumnType("INTEGER")
                        .HasColumnName("module_id_range_start");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Runtime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("runtime");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("runtime_templates", (string)null);
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.RuntimeTemplateDefaultModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("module_id");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordering");

                    b.Property<int>("RuntimeTemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("runtime_template_id");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.HasIndex("RuntimeTemplateId", "Ordering");

                    b.HasIndex("RuntimeTemplateId", "ModuleId")
                        .IsUnique();

                    b.ToTable("runtime_template_default_modules", (string)null);
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.TemplateFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordering");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("TemplateFolderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("template_folder_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateFolderId", "Ordering");

                    b.HasIndex("TemplateFolderId", "Path")
                        .IsUnique();

                    b.ToTable("template_files", (string)null);
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.TemplateModuleFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordering");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("TemplateModuleFolderId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("template_module_folder_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateModuleFolderId", "Ordering");

                    b.HasIndex("TemplateModuleFolderId", "Path")
                        .IsUnique();

                    b.ToTable("template_module_files", (string)null);
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.TemplateModuleFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordering");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Ordering");

                    b.ToTable("template_module_folders", (string)null);
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.TemplateFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordering");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("path");

                    b.Property<int>("TemplateId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Ordering");

                    b.ToTable("template_folders", (string)null);
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.WellKnownDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("DepId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_id");

                    b.Property<string>("DepName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_name");

                    b.Property<string>("DepPublisher")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_publisher");

                    b.Property<string>("DepVersionDefault")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("dep_version_default");

                    b.Property<int>("Ordering")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ordering");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("well_known_dependencies", (string)null);
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.ModuleDependency", b =>
                {
                    b.HasOne("ALDevToolbox.Domain.Entities.Module", "Module")
                        .WithMany("Dependencies")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.RuntimeTemplateDefaultModule", b =>
                {
                    b.HasOne("ALDevToolbox.Domain.Entities.Module", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ALDevToolbox.Domain.Entities.RuntimeTemplate", "Template")
                        .WithMany("DefaultModules")
                        .HasForeignKey("RuntimeTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.TemplateFile", b =>
                {
                    b.HasOne("ALDevToolbox.Domain.Entities.TemplateFolder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("TemplateFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.TemplateModuleFile", b =>
                {
                    b.HasOne("ALDevToolbox.Domain.Entities.TemplateModuleFolder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("TemplateModuleFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.TemplateModuleFolder", b =>
                {
                    b.HasOne("ALDevToolbox.Domain.Entities.RuntimeTemplate", "Template")
                        .WithMany("ModuleFolders")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.TemplateFolder", b =>
                {
                    b.HasOne("ALDevToolbox.Domain.Entities.RuntimeTemplate", "Template")
                        .WithMany("Folders")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.Module", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.RuntimeTemplate", b =>
                {
                    b.Navigation("DefaultModules");

                    b.Navigation("Folders");

                    b.Navigation("ModuleFolders");
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.TemplateFolder", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("ALDevToolbox.Domain.Entities.TemplateModuleFolder", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
