// <auto-generated />
using ALDevToolbox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ALDevToolbox.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260601000000_AddObjectExplorerTables")]
    partial class AddObjectExplorerTables
    {
        // Intentionally empty — matches the project's hand-rolled-migration
        // pattern (see InitialCreate.Designer.cs for the rationale). Schema
        // drift surfaces when the migration runs against a fresh database.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
