// <auto-generated />
using ALDevToolbox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ALDevToolbox.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602000000_DropBaseAppTables")]
    partial class DropBaseAppTables
    {
        // Intentionally empty — matches the project's hand-rolled-migration
        // pattern (see InitialCreate.Designer.cs for the rationale).
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
