// <auto-generated />
using ALDevToolbox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ALDevToolbox.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515000000_AddCodeWorkspaceJson")]
    partial class AddCodeWorkspaceJson
    {
        // Intentionally empty — see InitialCreate.Designer.cs for the
        // hand-rolled-migration rationale (the model snapshot is not the
        // source of truth in this project).
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
