// <auto-generated />
using ALDevToolbox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ALDevToolbox.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260515000000_AddOrganizationConfiguration")]
    partial class AddOrganizationConfiguration
    {
        // The full target model is reproduced in <c>AppDbContextModelSnapshot</c>;
        // EF reads it from there at design time. At runtime the [Migration]
        // attribute above is all that's required to apply <c>Up</c> / <c>Down</c>.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
