// <auto-generated />
using ALDevToolbox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ALDevToolbox.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260510000000_InitialCreate")]
    partial class InitialCreate
    {
        // The model snapshot is intentionally left empty here — see the same
        // pattern in the M14/M15 designer files this migration replaces. EF's
        // pending-model-changes warning is suppressed in Program.cs because of
        // it. Schema drift surfaces when the migration runs against a fresh
        // database, not via the snapshot.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
