// <auto-generated />
using ALDevToolbox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ALDevToolbox.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260517000000_AddObjectExplorer")]
    partial class AddObjectExplorer
    {
        // Intentionally empty — see InitialCreate.Designer.cs for the
        // hand-rolled-migration rationale.
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
