using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ALDevToolbox.Data.Migrations
{
    /// <inheritdoc />
    public partial class MovePlatformFilesToOrgFiles : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Promote the three workspace-root platform files (.gitignore, the
            // shared ruleset, the README stub) from generator-side embedded
            // resources into per-org `organization_files` rows the admin can
            // see, edit, and opt templates into. Backfills existing orgs and
            // joins them to every existing template so current behaviour is
            // preserved. New orgs are seeded by AccountService at signup time;
            // new templates start without these joins so admins explicitly
            // opt-in.
            //
            // Idempotent: skips orgs that already have a row at the path, and
            // joins that already exist for (template, file).

            migrationBuilder.Sql(@"
                INSERT INTO organization_files (organization_id, path, content, mustache_enabled, ordering, updated_at)
                SELECT o.id, '.gitignore',
                    $platfile$# AL build output
*.app
.alcache/
.alpackages/
.altestrunner/
.snapshots/
.netpackages/
rad.json
*.tmp

# VS Code
.vscode/launch.json
.vscode/.alcache/

# OS
Thumbs.db
ehthumbs.db
Desktop.ini
.DS_Store
$platfile$,
                    false, 1000, now()
                FROM organizations o
                WHERE NOT EXISTS (
                    SELECT 1 FROM organization_files f
                    WHERE f.organization_id = o.id AND f.path = '.gitignore'
                );
            ");

            migrationBuilder.Sql(@"
                INSERT INTO organization_files (organization_id, path, content, mustache_enabled, ordering, updated_at)
                SELECT o.id, '.assets/rulesets/Company.ruleset.json',
                    $platfile${
    ""name"": ""Company default rules"",
    ""description"": ""Baseline ruleset shipped by AL Dev Toolbox. Customise as your team's standards evolve."",
    ""generalAction"": ""Default"",
    ""includedRuleSets"": [],
    ""rules"": [
        { ""id"": ""AA0008"", ""action"": ""Warning"", ""justification"": ""Function calls should have parentheses."" },
        { ""id"": ""AA0072"", ""action"": ""Warning"", ""justification"": ""Object names should not exceed 30 characters."" },
        { ""id"": ""AA0074"", ""action"": ""Warning"", ""justification"": ""TextConst variable names should follow naming conventions."" },
        { ""id"": ""AA0137"", ""action"": ""Warning"", ""justification"": ""Variables should be used."" },
        { ""id"": ""AA0150"", ""action"": ""Warning"", ""justification"": ""Internal procedures should be marked as such."" },
        { ""id"": ""AA0228"", ""action"": ""Warning"", ""justification"": ""Procedures with a Cyclomatic complexity over 8 should be refactored."" },
        { ""id"": ""AS0011"", ""action"": ""Warning"", ""justification"": ""Each AL object should declare a namespace."" }
    ]
}
$platfile$,
                    false, 1001, now()
                FROM organizations o
                WHERE NOT EXISTS (
                    SELECT 1 FROM organization_files f
                    WHERE f.organization_id = o.id AND f.path = '.assets/rulesets/Company.ruleset.json'
                );
            ");

            migrationBuilder.Sql(@"
                INSERT INTO organization_files (organization_id, path, content, mustache_enabled, ordering, updated_at)
                SELECT o.id, 'README.md',
                    $platfile$# {{workspace_name}}

Generated by AL Dev Toolbox.
$platfile$,
                    true, 1002, now()
                FROM organizations o
                WHERE NOT EXISTS (
                    SELECT 1 FROM organization_files f
                    WHERE f.organization_id = o.id AND f.path = 'README.md'
                );
            ");

            // Join every existing live template to the three platform files
            // so current behaviour (always-emitted) is preserved. New
            // templates created after this migration start without these
            // joins — admins opt them in explicitly via the editor.
            migrationBuilder.Sql(@"
                INSERT INTO runtime_template_included_files
                    (organization_id, runtime_template_id, organization_file_id, ordering)
                SELECT
                    t.organization_id,
                    t.id,
                    f.id,
                    f.ordering
                FROM runtime_templates t
                JOIN organization_files f
                    ON f.organization_id = t.organization_id
                WHERE t.deleted_at IS NULL
                  AND f.path IN ('.gitignore', '.assets/rulesets/Company.ruleset.json', 'README.md')
                  AND NOT EXISTS (
                      SELECT 1 FROM runtime_template_included_files j
                      WHERE j.runtime_template_id = t.id
                        AND j.organization_file_id = f.id
                  );
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Drop the joins first, then the rows. Safe because we own the
            // exact paths; admin-authored files at different paths are
            // untouched.
            migrationBuilder.Sql(@"
                DELETE FROM runtime_template_included_files
                WHERE organization_file_id IN (
                    SELECT id FROM organization_files
                    WHERE path IN ('.gitignore', '.assets/rulesets/Company.ruleset.json', 'README.md')
                );
            ");

            migrationBuilder.Sql(@"
                DELETE FROM organization_files
                WHERE path IN ('.gitignore', '.assets/rulesets/Company.ruleset.json', 'README.md');
            ");
        }
    }
}
