// <auto-generated />
using ALDevToolbox.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace ALDevToolbox.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        // Intentionally empty — the model is hand-rolled in OnModelCreating
        // and the migrations are written by hand. See the comment on
        // InitialCreate.Designer.cs.
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
        }
    }
}
